name: mirror-to-gitee
on:
  push:
    branches:
    - main
    - dev
  delete:

jobs:
  main-to-gh-pages:
    runs-on: ubuntu-latest
    steps:                          
    - name: 'checkout'
      uses: actions/checkout@v2
        
    - name: 'mirror to gitee'
      uses: pixta-dev/repository-mirroring-action@v1
      with:
        target_repo_url:
          git@gitee.com:jellyblack/bili-live-monitor.git
        ssh_private_key:
          ${{ secrets.SSH_GITEE }}